# Generated by Django 5.1.2 on 2024-11-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinkleruser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pinkleruser',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'М'), ('Женский', 'Ж')], default='М', max_length=7),
        ),
    ]
