# Generated by Django 5.1.2 on 2024-11-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_pinkleruser_avatar_alter_pinkleruser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinkleruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
