# Generated by Django 5.1.2 on 2024-11-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_pinkleruser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinkleruser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/default_avatar.png', null=True, upload_to='users/avatars/'),
        ),
    ]
