# Generated by Django 5.1.2 on 2024-11-12 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
    ]
